language: node_js

node_js:
- '8'

sudo: required

services:
- docker

env:
  matrix:
    - ARCH=arm

before_install:
- date
- docker login --username=${DOCKER_USER} --password=${DOCKER_PASS}

install:
- make install

script:
- make test
- make build

deploy:
  provider: script
  script: make publish
  skip_cleanup: true
  on:
    tags: true
  repo: riggerthegeek/function-distance-finder
